# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# hook_add = '''
#   source ~/.config/nvim/plugins/deoplete.vim
# '''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#snippets_directory='~/.nvim/snippets'
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
